/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ColorItem: typeof import('./src/components/ColorItem.vue')['default']
    ColorList: typeof import('./src/components/ColorList.vue')['default']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElSelectV2: typeof import('element-plus/es')['ElSelectV2']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    RecycleScroller: typeof import('./src/components/RecycleScroller.vue')['default']
    RecycleScroller2: typeof import('./src/components/RecycleScroller2.vue')['default']
    RecycleScroller3: typeof import('./src/components/RecycleScroller3.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ViewWrapper: typeof import('./src/components/ViewWrapper.vue')['default']
  }
}
